### ISSUE TITLE
When ranking players, only players from the game are ranked

### ISSUE THREAD

**Issue by CForrest97** [rwalle61/leaguetracker#19]
When updating a league with options:
`
{
	"season": {
		"seasonName": "Pool Season 1",
		"players": [{
			"name": "Richard",
			"score": 1000,
			"wins": 0,
			"losses": 0,
			"rank": 2
		}, {
			"name": "Craig",
			"score": 1000,
			"wins": 0,
			"losses": 0,
			"rank": 2
		}, {
			"name": "Tom",
			"score": 1001,
			"wins": 0,
			"losses": 0,
			"rank": 1
		}]
	},
	"game": {
		"namesOfWinners": ["Craig"],
		"namesOfLosers": ["Richard"]
	}
}
`
Tom's rank stays at 1 and Craig and Richards ranks are based on just each other, not considering Toms score.
So the result is
Richard -> 2nd
Craig -> 1st
Tom -> 1st

**Comment by rwalle61** [comment]
fixed by #20
